### ISSUE TITLE
Unexpected error when unlocking/retiring /relocking a feature

### ISSUE THREAD

**Issue by rennyeb** [featurehub-io/featurehub#1094]
![RetireLockedFeature](https://github.com/featurehub-io/featurehub/assets/2862511/2a032ea0-73e7-41ef-8172-72b3a47f1d41)
**Describe the bug**

 Which area does this issue belong to?

* [X] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Create a boolean feature 
2. Edit the feature to make it "locked" (if it is not already)
3. Edit the feature, and in one operation a) unlock it b) check the "Retired" box c) re-lock it
4. Click "Save"
5. "An unexpected error occurred!", with these details:

ApiException 400:  Stack trace: ApiException 400: 
    at Object.c (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:4925:3)
    at http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:107391:23
    at b9z.a (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:6226:62)
    at b9z.$2 (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:51927:14)
    at b8_.$1 (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:51921:21)
    at b2b.aTo (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:52821:34)
    at b2b.VC (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:52823:21)
    at aXL.$0 (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:52276:11)
    at Object.Dl (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:6321:40)
    at aC.yx (http://54.237.75.159:8085/main-748bd6b2b447bc5d4dde70ac2197a934e07cce433ebe22e16db4c4d475cfd0c3.js:52209:3)

**Expected behavior**
The change to the feature (i.e. to retire it, and have it remain locked) should be saved without error.

**Screenshots**
Screen recording attached.

**Versions**
 - FeatureHub version: I am evaluating FeatureHub v1.7.0 using the docker image.
 - OS: Windows (for the browser), Linux for the docker installation
 - Browser: Chrome

docker ps: 591d7cbf42cd   featurehub/party-server:latest
Docker version 24.0.5, build ced0996

**Comment by IrinaSouth** [comment]
Hi @rennyeb,

Thank you for trying out our new release. 

The bug you are describing is actually expected behaviour, I will try to explain what happened in this case. 

When you have a feature "locked" and attempt to unlock and retire (or set a new value) and then "lock" at the same time, the payload that gets sent to the server gets rejected, because it is still "locked" on the server. So in order for a new value to be accepted: 
1) Unlock the feature first and save
2) Open feature editing screen, change value/retire and lock and save

I do recognise that we should improve our UI a bit to suit this flow better. We will take a look in our next versions how we can make it less prone to this error being thrown.

Cheers

**Comment by rennyeb** [comment]
Thanks for the quick reply!  I acknowledge that it's a UI flow issue rather than anything more serious.
