### ISSUE TITLE
getting NullPointerException

### ISSUE THREAD

**Issue by pontamilselvan** [featurehub-io/featurehub#542]
Hi , i am using java-client-core-2.2 and java-client-jersey-2.2.

Trying with below code... 

```
			String featureHubUrl = "http://localhost:8080/";
			String apiKey = "default/c540dcaa-3568-49ff-8a1e-bcc03aec6875/WDPJDg1nOgkfcYfgGu3B7NzdNkjJ58K2IPJoVepxvBWORmfTeYUFDblPGzNvPZyhxWUi7XdeJXP5heKk";

			FeatureHubConfig fhConfig = new EdgeFeatureHubConfig(featureHubUrl, apiKey);
			System.out.println("RealtimeUrl:"+fhConfig.getRealtimeUrl());
			fhConfig.init();
```
		

getting below error/exception

```
RealtimeUrl:http://localhost:8080/features/default/c540dcaa-3568-49ff-8a1e-bcc03aec6875/WDPJDg1nOgkfcYfgGu3B7NzdNkjJ58K2IPJoVepxvBWORmfTeYUFDblPGzNvPZyhxWUi7XdeJXP5heKk
15:35:20.617 [main] ERROR io.featurehub.client.EdgeFeatureHubConfig - Failed to initialize FeatureHub client
java.lang.NullPointerException: null
	at io.featurehub.client.jersey.JerseyClient.contextChange(JerseyClient.java:255) ~[java-client-jersey-2.2.jar:?]
	at io.featurehub.client.ServerEvalFeatureContext.build(ServerEvalFeatureContext.java:46) ~[java-client-core-2.2.jar:?]
	at io.featurehub.client.EdgeFeatureHubConfig.init(EdgeFeatureHubConfig.java:59) [java-client-core-2.2.jar:?]
	at JerseyClientSample2.display(JerseyClientSample2.java:25) [bin/:?]
	at JerseyClientSample2.main(JerseyClientSample2.java:41) [bin/:?]	
```

**Comment by rvowles** [comment]
hey, looking at this now

**Comment by rvowles** [comment]
so I have a fix for this, i now need to roll it out for you.

**Comment by rvowles** [comment]
Hi there! This issue is now resolved, please update to the latest Jersey client which is... 2.3

**Comment by pontamilselvan** [comment]
hi , where can i get 2.3 jar? i am not seeing it in maven repository

**Comment by rvowles** [comment]
It normally takes a couple of hours to get to Central, so you may have been hit by that delay 🤔 it's definitely there now

https://search.maven.org/artifact/io.featurehub.sdk/java-client-jersey
